-- WAREHOUSES:
define warehouse ANALYST_WH_{{ ENV }}
    WAREHOUSE_SIZE = SMALL
    MAX_CLUSTER_COUNT = 3
    MIN_CLUSTER_COUNT = 1
    SCALING_POLICY = ECONOMY
    AUTO_SUSPEND = 1200;

define warehouse DATA_SCIENCE_WH_{{ ENV }}
    WAREHOUSE_SIZE = LARGE
    AUTO_SUSPEND = 60;
